import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from './sideBar/page'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row">
          <div className="basis-/4">
            <SideBar /> 
          </div>
          <div className="basis-3/4">
            {children}
          </div>
        </div>
        </body>
    </html>
  )
}
